# 开启Travis CI任务, 提交后自动生成测试报告。
language: cpp
os:
  - linux

compiler:
  - gcc

branches:
  only:
    - master

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
    - secure: "c9JQDX7c/RAQYUuaW9bGsORRFLFWpiq/C00TGMCHOZUkuI2VUNqh2H8c99QIuJHHXWoVau0727wGRGBtcg3kAeJMsnnkelbGc9Ca8Uu6MhQRN3VqlvcSSCuz3R6JNxmQWaWbSxEwyHsljzMwubeevMkztVFXXyj6VImKjkrwFRgJGf4MheZ5yi0IVQah1rZ8spqktMOYCJiGRODJCK8IhrfUYHqwv31CYO3GGf6Iq4HbArAMwfNovqSWxAwJ5oHhEFEb+gsrGIPG5+nRxs1Sb9pDJtqLHajQq85TVGK8qUaKi7nzcpbw9qegomd7iMadq7518ZSXJN/5cY4A1t4fbZdLy8mU5IdAz4P4SqLkO7SSjmyLxD5iBYoHftXZ6/H+b/l6pUXskCrj4YZBdiyorD6TkKfw4+VkLaPwjyRHFY2j8rxUhGcptAoQZDIYsTL95WnCj/njPbipBvZ9NtNu7qQOEDwrmCCLElfFqV6m1bKVwzp/iOe/B2C9GUVJ+QQUsinb22YWQ44vNWtYxU2fRy56AjfBiiufkJA5VVFZ36BxeKsSaMkSKvZDvbEYRyHznhpGWVDZKiB3+xR3cukhcvC7X+Aj90vNh/PxGFU7bums5uZdwM8gF5fGJ0rAXYLqKPaJknA1OLSr5xFA6FBoByBaHxdAns54cNBqor2Mxks="

before_install:
    - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
    - sudo apt-get update -y
    - sudo apt-get install libboost-all-dev -y
    - sudo apt-get install aptitude -y
    - aptitude search boost -y
    - sudo apt-get install scons -y

script: if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then make ; fi

addons:
  coverity_scan:
    project:
      name: "liuchao412/async-or-coroutine-fastcgi"
      description: "Build submitted via Travis CI"
    notification_email: liuchao412@foxmail.com
    build_command_prepend: "scons -c"
    build_command: "scons"
    branch_pattern: master
